### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by cfangmeier** [aminnj/matplottery#2]
I ran into a couple issues getting this working in Python 3.

Issue 1: There are a few python2 style print statements. Wrapping them in parens and including

`from __future__ import print_function`

should fix it.

Issue 2: In python3 the `__div__` magic method was replaced with `__truediv__` and `__floordiv__` which correspond to the `/` and `//` operators, respectively. This is a problem for the Hist1D class since it implements `__div__`. Python 3 support could be easily added by also implementing `__truediv__` and pointing it explicitely to `__div__`, or the other way around.

**Comment by cfangmeier** [comment]
Now that I think of it, I think Issue 2 may also be fixed by `from __future__ import division`.

**Comment by aminnj** [comment]
Solved by https://github.com/aminnj/matplottery/commit/42a5d6a1c74c90e3504d7e5ee05441106a58bfbe . Needed to do `__truediv__ = __div__`
