### ISSUE TITLE
Consider replacing getters with properties

### ISSUE THREAD

**Issue by cfangmeier** [aminnj/matplottery#4]
for example in `Hist1D`,

```python
def get_errors(self):
    return self._errors
```
would be replaced with
```python
@property
def errors(self):
    return self._errors
```

And the usage would change from
```python
h.get_errors()
```
to
```python
h.errors
```

Personally, I would consider this to be more "pythonic", but at some level it's really a stylistic choice. Thoughts?

**Comment by aminnj** [comment]
Good point. I did this in https://github.com/aminnj/matplottery/commit/130f9ee0ce9432c008e4061171c6b0ffd35ab5ec . I kept the old `get_` ones for compatibility, but added `.errors`, `.counts`, `.edges` properties, and made these changes in `plotter.py` as well.
